# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmUser',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('full_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
