# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    model = apps.get_model("users", "CurrentStatusModel")
    db_alias = schema_editor.connection.alias
    model.objects.using(db_alias).bulk_create([
        model(is_active=False),
    ])


def reverse_func(apps, schema_editor):
    model = apps.get_model("users", "CurrentStatusModel")
    db_alias = schema_editor.connection.alias
    Country.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='admuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
