# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171114_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='admuser',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
