# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admuser',
            name='token',
            field=models.CharField(
                default=users.models.AdmUser.get_default_token, max_length=100),
        ),
    ]
