# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171115_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='admuser',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
